# Generated by Django 3.2.9 on 2021-11-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=40)),
                ('Message', models.TextField()),
            ],
        ),
    ]
